<?php
/**
 * KeyCash
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * @category    Keycash
 * @package     Keycash_Core
 * @copyright   Copyright (c) 2017 KeyCash. (https://www.keycash.co/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $helper = Mage::helper('keycash_core') ?>
<?php $verificationData = $this->getVerificationData() ?>
<div>
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo $helper->__('KeyCash Verification') ?></h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <?php foreach ($verificationData as $item): ?>
                <tr>
                    <td class="label"><label><?php echo $item['label'] ?></label></td>
                    <td class="value"><strong><?php echo $item['value'] ?></strong></td>
                </tr>
                <?php endforeach ?>
                <?php if ($this->isVerificationStatusRetrieveButtonEnabled()): ?>
                <tr>
                    <?php $buttonLabel = $helper->__('Get Verification Status') ?>
                    <td class="label"><label><?php echo $buttonLabel ?></label></td>
                    <td class="value">
                        <button type="button" class="scalable" title="<?php echo $buttonLabel ?>"
                            onclick="setLocation('<?php echo $this->getVerificationStatusRetrieveRequestUrl() ?>')">
                            <span><span><span><?php echo $helper->__('Run') ?></span></span></span>
                        </button>
                    </td>
                </tr>
                <?php endif ?>
                <?php if ($this->isOrderVerifyButtonEnabled()): ?>
                <tr>
                    <?php $buttonLabel = $helper->__('Verify Order') ?>
                    <td class="label"><label><?php echo $buttonLabel ?></label></td>
                    <td class="value">
                        <button type="button" class="scalable" title="<?php echo $buttonLabel ?>"
                            onclick="setLocation('<?php echo $this->getOrderVerifyUrl() ?>')">
                            <span><span><span><?php echo $helper->__('Run') ?></span></span></span>
                        </button>
                    </td>
                </tr>
                <?php endif ?>
            </table>
        </div>
    </div>
</div>
<div class="clear"></div>
