<?php
/**
 * KeyCash
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * @category    Keycash
 * @package     Keycash_Core
 * @copyright   Copyright (c) 2017 KeyCash. (https://keycash.co)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $helper = Mage::helper('keycash_core') ?>
<div class="order-info">
    <h2 class="table-caption"><?php echo $helper->__('KeyCash') ?></h2>
</div>
<div class="order-info">
    <div class="col-wrapper order-info-box">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $helper->__('Verification Status') ?></h2>
            </div>
            <div class="box-content">
                <address><?php echo $this->getVerificationState() ?></address>
            </div>
        </div>
    </div>
</div>
